use_frameworks!

platform :ios, '9.0'

target 'WebviewComponent_Example' do
  pod 'WebviewComponent', :path => '../'
  target 'WebviewComponent_Tests' do
    inherit! :search_paths

    
  end
end
pre_install do |installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
